[[libfoo]]
arch = "x86_64"
git-tree-sha1 = "37e9420ad5369a10f5155d16e1cd409ef5182be3"
os = "macos"

    [[libfoo.download]]
    sha256 = "6a0feec8eaa9f53dba40ba8ad218aa265e4ea425e3db7ad812d6420e85884c88"
    url = "https://github.com/barche/libfoo_jll.jl/releases/download/libfoo-v5.13.2+0/libfoo.v5.13.2.x86_64-apple-darwin14.tar.gz"
[[libfoo]]
arch = "x86_64"
git-tree-sha1 = "ea71c058454fdf0fb0bd42dd8dd0be85d993aa2c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[libfoo.download]]
    sha256 = "f46d555c8ad463ff5ec133527df86cd8468d46268d41ad4e30b12a73b62fa142"
    url = "https://github.com/barche/libfoo_jll.jl/releases/download/libfoo-v5.14.0+0/libfoo.v5.14.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[libfoo]]
arch = "powerpc64le"
git-tree-sha1 = "d31e3634c1b9be9ae01052839ff471e6ed2e508f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[libfoo.download]]
    sha256 = "4ecbe78e2563964d11425a2beade2e3114b8456c584a7b259dc13e8b034979df"
    url = "https://github.com/barche/libfoo_jll.jl/releases/download/libfoo-v5.15.0+0/libfoo.v5.15.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[libfoo]]
arch = "armv7l"
git-tree-sha1 = "a662ded1f35a6254b68d8d78cf3f91a0048b5ffd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[libfoo.download]]
    sha256 = "20794f885d9d9638487b92eaf725229c2adaf9fd636080d845c5f3b72bdd528a"
    url = "https://github.com/barche/libfoo_jll.jl/releases/download/libfoo-v5.15.0+0/libfoo.v5.15.0.arm-linux-gnueabihf-libgfortran3.tar.gz"
[[libfoo]]
arch = "x86_64"
git-tree-sha1 = "dd0d933dda54f14c21dd69957988b298b3c3c5e2"
libgfortran_version = "3.0.0"
os = "macos"

    [[libfoo.download]]
    sha256 = "e64d72aa25b05e42917ee4912f335de54ef7bba585317b9f1579182388ca0933"
    url = "https://github.com/barche/libfoo_jll.jl/releases/download/libfoo-v5.15.0+0/libfoo.v5.15.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[libfoo]]
arch = "aarch64"
git-tree-sha1 = "d46d00b9349118bf2287dcd15a0d65027ccfc8ae"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[libfoo.download]]
    sha256 = "ff0f6971ae768ba69509fe6b78b5b0a52f79dde4675ba9fef404f71ae901e6db"
    url = "https://github.com/barche/libfoo_jll.jl/releases/download/libfoo-v5.15.0+0/libfoo.v5.15.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[libfoo]]
arch = "i686"
git-tree-sha1 = "4717d04029545122494b837bd7a129390ac5ded5"
libgfortran_version = "3.0.0"
os = "windows"

    [[libfoo.download]]
    sha256 = "5cfb3883dac16b73af9245dc88424463694a3fbb0079e9d42db10a495ef99b79"
    url = "https://github.com/barche/libfoo_jll.jl/releases/download/libfoo-v5.15.0+0/libfoo.v5.15.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[libfoo]]
arch = "x86_64"
git-tree-sha1 = "1a3a929050bbaa56a4aee2afcbc71d36c317717b"
libc = "glibc"
os = "linux"

    [[libfoo.download]]
    sha256 = "d4b09e4d59c37f4d364be48e7b47eee17f80ca866044dacde7aebfef57041698"
    url = "https://github.com/barche/libfoo_jll.jl/releases/download/libfoo-v5.15.0+0/libfoo.v5.15.0.x86_64-linux-gnu.tar.gz"
